### ISSUE TITLE
unknown type name NexTouch

### ISSUE THREAD

**Issue by adithyak21** [alperssl/Nextion-Hmi-Library-for-STM32-Platform#1]
I am trying to replace the arduino code for nextion to STM32 in STM32 IDE i am facing a problem in 
**void nexLoop(NexTouch *nex_listen_list[]);**

![Capture](https://user-images.githubusercontent.com/59138730/74607921-f4f98880-5102-11ea-9c42-be0a70abc534.PNG)

Kindly help me if i am doing it in a wrong way

**Comment by alperssl** [comment]
write me directly, I will help u.
mail@alpersuslu.com
